# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./humhum.h
SOURCES += ./humhum.cpp \
    ./main.cpp
FORMS += ./humhum.ui
RESOURCES += humhum.qrc
